//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CIDRInjection) DeepCopyInto(out *CIDRInjection) {
	*out = *in
	in.IdentityLabelPurposeSelector.DeepCopyInto(&out.IdentityLabelPurposeSelector)
	if in.Injections != nil {
		in, out := &in.Injections, &out.Injections
		*out = make([]SingleCIDRInjection, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CIDRInjection.
func (in *CIDRInjection) DeepCopy() *CIDRInjection {
	if in == nil {
		return nil
	}
	out := new(CIDRInjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenerIPAMConfig) DeepCopyInto(out *GardenerIPAMConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenerIPAMConfig.
func (in *GardenerIPAMConfig) DeepCopy() *GardenerIPAMConfig {
	if in == nil {
		return nil
	}
	out := new(GardenerIPAMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GardenerIPAMConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenerIPAMConfigList) DeepCopyInto(out *GardenerIPAMConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GardenerIPAMConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenerIPAMConfigList.
func (in *GardenerIPAMConfigList) DeepCopy() *GardenerIPAMConfigList {
	if in == nil {
		return nil
	}
	out := new(GardenerIPAMConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GardenerIPAMConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenerIPAMConfigSpec) DeepCopyInto(out *GardenerIPAMConfigSpec) {
	*out = *in
	if in.ParentCIDRs != nil {
		in, out := &in.ParentCIDRs, &out.ParentCIDRs
		*out = make(map[string][]CIDR, len(*in))
		for key, val := range *in {
			var outVal []CIDR
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]CIDR, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenerIPAMConfigSpec.
func (in *GardenerIPAMConfigSpec) DeepCopy() *GardenerIPAMConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GardenerIPAMConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleCIDRInjection) DeepCopyInto(out *SingleCIDRInjection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleCIDRInjection.
func (in *SingleCIDRInjection) DeepCopy() *SingleCIDRInjection {
	if in == nil {
		return nil
	}
	out := new(SingleCIDRInjection)
	in.DeepCopyInto(out)
	return out
}
